files:
  include: 'scss/**/*.scss'
rules:
  indentation:
    - 1
    - size: 'tab'
  class-name-format:
    - 1
    - ignore:
        - gforms_edit_form
        - field_hover
        - field_selected
  nesting-depth:
    - 1
    - max-depth: 3
  no-ids:
    - 0
  property-sort-order:
    - 1
    - order:
        - background
        - background-color
        - background-image
        - border
        - border-top
        - border-top-width
        - border-right
        - border-right-color
        - border-right-width
        - border-bottom
        - border-bottom-width
        - border-left
        - border-left-width
        - border-radius
        - border-spacing
        - box-shadow
        - clear
        - clip
        - color
        - content
        - cursor
        - display
        - float
        - font-family
        - font-size
        - font-style
        - font-weight
        - line-height
        - list-style
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - max-width
        - padding
        - outline
        - overflow
        - position
        - top
        - right
        - bottom
        - left
        - speak
        - text-indent
        - width
        - height
